# Sample .travis.yml for R projects

language: r
r:
  - release
  - devel

cache: packages

sudo: required

dist: trusty

branches:
  only:
    - devel
    - master

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libprotobuf-dev protobuf-compiler libv8-3.14-dev
 
warnings_are_errors: false

r_packages:
  - rgdal
  - roxygen2
  - rmarkdown
