# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CTCRWNLL <- function(y, Hmat, Qmat, Tmat, noObs, activity, a, P) {
    .Call('crawl_CTCRWNLL', PACKAGE = 'crawl', y, Hmat, Qmat, Tmat, noObs, activity, a, P)
}

CTCRWPREDICT <- function(y, Hmat, Qmat, Tmat, noObs, activity, a, P) {
    .Call('crawl_CTCRWPREDICT', PACKAGE = 'crawl', y, Hmat, Qmat, Tmat, noObs, activity, a, P)
}

