# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

makeT <- function(b, delta) {
    .Call('crawl_makeT', PACKAGE = 'crawl', b, delta)
}

makeQ <- function(b, sig2, delta) {
    .Call('crawl_makeQ', PACKAGE = 'crawl', b, sig2, delta)
}

CTCRWNLL <- function(y, Hmat, Qmat, Tmat, noObs, active, a, P) {
    .Call('crawl_CTCRWNLL', PACKAGE = 'crawl', y, Hmat, Qmat, Tmat, noObs, active, a, P)
}

CTCRWPREDICT <- function(y, Hmat, Qmat, Tmat, noObs, active, a, P) {
    .Call('crawl_CTCRWPREDICT', PACKAGE = 'crawl', y, Hmat, Qmat, Tmat, noObs, active, a, P)
}

CTCRWSAMPLE <- function(y, Hmat, Qmat, Tmat, noObs, active, a, P) {
    .Call('crawl_CTCRWSAMPLE', PACKAGE = 'crawl', y, Hmat, Qmat, Tmat, noObs, active, a, P)
}

